name: Generate Dinosauroscopes

on:
  schedule:
    - cron: '20 0 * * *'  # every day at 00:20 UTC
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm install node-fetch@2

      - name: Generate today’s dinosauroscopes
        env:
          GH_AI_TOKEN: ${{ secrets.GH_AI_TOKEN }}  # your GitHub token
        run: node ./scripts/generate-dinosauroscopes.js

      - name: Commit & push JSON
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add dinosauroscopes/*.json
          git commit -m "📜 Dinosauroscopes for $(date +%F)" || echo "No changes to commit"
          git push